astrowalker/album/urls.py
from django.urls import path,include
from . import views

app_name = 'album'

urlpatterns = [
    path('showall/',views.showall,name='showall'),
]

astrowalker/articles/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from .views import ArticleListView,ArticleDetailView,PostArchiveView,TagSearchedListView

app_name = 'articles'
urlpatterns = [
    path('',ArticleListView.as_view(),name='article.list'),
    path('<int:pk>/',ArticleDetailView.as_view(),name='article'),
    path('archive/',PostArchiveView.as_view(),name='post_archive'),
]

astrowalker/astrowalker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='top.html')),
    path('articles/',include('articles.urls')),
    # path('album/',include('album.urls')),
    path('about/',TemplateView.as_view(template_name='about.html')),
] 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

astrowalker/album/models.py
from django.db import models

class Image(models.Model):
    picture = models.ImageField(upload_to='images/')
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

astrowalker/articles/models.py
from django.db import models
from django.utils import timezone
# from taggit.managers import TaggableManager

TAGS = (("0","内容がない"),("1","科学"),("2","思考"),("3","プログラミング"),("4","出来事"))

class Tag(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=20)
    summary = models.TextField(blank=True)
    text = models.TextField(blank=False)
    date = models.DateTimeField(blank=False)
    photo = models.ImageField(upload_to='images/',default='defo_picture')
    sumnail = models.ImageField(upload_to='images/',default='defo_picture')
    tags = models.CharField(max_length=10,choices=TAGS,blank=True)
    # tags = models.ManyToManyField(Tag,blank=True)
    # tags = TaggableManager()

    def __str__(self):
        return self.title

class Comment(models.Model):
    name = models.CharField(max_length=20,blank=True)
    text = models.TextField()
    # target = models.ForeignKey(Post,on_delete=models.CASCADE)
    is_public = models.BooleanField(default=False)

    def __str__(self):
        return self.name

astrowalker/album/views.py
from django.shortcuts import render
from .models import Image

def showall(reqest):
    images = Image.objects.all()
    context = {'images':images}
    return render(reqest,'album/showall.html',context)

astrowalker/articles/views.py
from django.shortcuts import render
from .models import Post,Comment,Tag
from django.views.generic import ListView,DetailView,ArchiveIndexView
# from taggit.models import Tag
from django.template import RequestContext
from django.shortcuts import render_to_response


class ArticleListView(ListView):
    template_name = 'articles/article_list.html'
    model = Post
    paginate_by = 5

    def get_context_data(self,**kwargs):
        context = super(ArticleListView,self).get_context_data(**kwargs)
        post = self.model.objects.all()
        context['post'] = post

        default_data  = {
            'tags':0
        }
        return context

    def get_queryset(self):
        object_list = self.model.objects.all().order_by('-date')
        q_tags = self.request.GET.get('tags')
        # q_tags = 4
        if q_tags is not None:
            if q_tags != "":
                object_list = object_list.filter(tags=q_tags)
        return object_list

class ArticleDetailView(DetailView):
    template_name = 'articles/detail.html'
    model = Post
    context_object_name = 'article'

class PostArchiveView(ArchiveIndexView):
    model = Post
    date_field = 'date'
    allow_empty = True

class TagSearchedListView(ListView):
    template_name = 'articles/post_tagsearched.html'
    model = Post

astrowalker/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<body>
<div class="contents">
    <h1>管理者のあれこれ</h1>
    <p>名前：歩。苗字言うと一発で特定される。<br>
        出身：関西と東海のはざま<br>
        興味：物理、教育、スポーツ（やる方。観戦はあんまり。）<br>
        好きなもの：塩昆布<br>
        嫌いなもの：各種手続き（だるい）<br>
    </p>
    <h1>命名について</h1>
    ひょっとしたらセンスあるかもしれない。<br>
    自分の名前が「歩」で、将来の夢が宇宙飛行士だから造語命名。（将来の夢については今度記事書こう）<br>
    自分としては気に入ってるけど、他人からの評価はどうなんだろうね。
    <h1>このサイトのスタンス</h1>
    <p>前々からブログはやっといたほうがいいかなと思っていた。理由は色々ある。<br>
        Python忘れないためとか、備忘録とか、しばらく会ってない友達への近況報告とかあるけど、<br>
         1番の理由は自分の思考をどこかに残しておきたいという気持ちが強い。<br>
        だから、全然需要のないことも書いちゃうかもしれない。
    </p>
    <h1>サイト年表</h1>
    <p>2019/9/20 ベータ版作成</p>
    <h1>その他</h1>
    日記色が強いけど、気にせずどんどん書いていこう。
</div>
</body>

{% endblock %}

astrowalker/templates/album/showall.html
<h1>アルバム</h1>

{% for image in images %}
    <img src="{{ MEDIA_URL }}{{ image.picture }}" alt="" width="200">
    <h2>{{ image.title }}</h2>
{% endfor %}

astrowalker/templates/articles/article_list.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block content %}
<body>
<div class="left_bar">
<!-- <div class="recent_entries">
    <h1>直近記事</h1>
</div>                 -->
<div class="archive">
    <h1>アーカイブ</h1>
    <a href="archive/">アーカイブ一覧へ</a>

</div>            
</div>

<div class="right_bar">
<div class="tags">
    <h1>タグ検索</h1>
    <form action="" method="get" name="filter_form">
        
        <br><input type="radio" id="filter_tag" name="tags" value="0">内容がない
        <br><input type="radio" id="filter_tag" name="tags" value="1">科学
        <br><input type="radio" id="filter_tag" name="tags" value="2">思考
        <br><input type="radio" id="filter_tag" name="tags" value="3">プログラミング
        <br><input type="radio" id="filter_tag" name="tags" value="4">出来事
        
        <br>
        <button class="filter_button">絞り込み</button>
        <a href="/articles/">全件記事表示に戻る</a>
    </form>
    
</div>            
</div>

<div class="contents">
    <h1>記事</h1>
    {% for post in object_list %}
    <div class="article_list_detail">
        <div class="post_title_detail"><a href="{% url 'articles:article' post.pk %}">{{ post.title }}</a></div>
        <div class="post_date_detail">{{ post.date |date:"Y-m-j H:i:s"}}</div>
        <div class="post_img_detail"><img src="{{ post.sumnail.url }}" alt=""></div>
        <div class="post_tags_detail">カテゴリ：<strong class="post_tag">{{ post.get_tags_display }}</strong></div>
        
        <div class="post_summary_detail">{{ post.summary }}</div>
        <!-- <div class="post_text">{{ post.text | linebreaksbr }}</div> -->
    </div>
    {% endfor %}
    {% include "pagination.html" %}
</div>
</body>

{% endblock %}

astrowalker/templates/articles/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<body>


<div class="contents">
    <div class="article_list">
        <div class="post_img"><img src="{{ article.photo.url }}" alt=""></div>
        <div class="post_title">{{ article.title }}</div>
        <div class="post_tags">カテゴリ：<strong class="post_tag">{{ article.get_tags_display }}</strong></div>
        <div class="post_date">{{ article.date |date:"Y-m-j H:i:s"}}</div>
        <div class="post_summary">{{ article.summary }}</div>
        <div class="post_text">{{ article.text | linebreaksbr }}</div>
        
    </div>
    <div class="referer_button">
    <a href="{{request.META.HTTP_REFERER}}">戻る</a>
    </div>
</div>
</body>

{% endblock %}

astrowalker/templates/articles/post_archive.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="contents">
<h1>全ての記事</h1>
{% for dt in date_list %}
    <h2>{{ dt.year }}年</h2>
{% endfor %}

{% for post in latest %}
  <p><a href="{% url 'articles:article' post.pk %}">{{ post.date |date:"Y-m-j" }} {{ post.title }}</a></p>
{% endfor %}

<a href="/articles/">
    <div>記事一覧に戻る</div></a>
</div>
{% endblock %}

astrowalker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>宇宙"歩"行士の思考軌跡</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- フォントオーサムを使う -->
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/favicon.gif' %}">
</head>
<body>
    <ul>
        <li><a href="/"><i class="fas fa-home"></i>Home</a></li>    
        <li><a href="/articles/"><i class="fas fa-book"></i>Diary</a></li>
        <li><a href="/about/"><i class="fas fa-address-card"></i>About</a></li>
        <li><p><i class="fas fa-rocket"></i>宇宙”歩”行士の思考軌跡</p></li>
    </ul>            
    {% block content %}
    {% endblock %}
</body>
<footer>

    <p>Copyright(c) 宇宙"歩"行士の思考軌跡 All Rights Reserved.</p>
    <a href="/admin/">ログイン</a>
</footer>
</html>

astrowalker/templates/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}
    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
      <span class="page-link">
        {{ num }}
        <span class="sr-only">(current)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

astrowalker/templates/top.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    
<body>
    <div class="title_img">
        <div class="top_title">My Way of Thinking to Be ASTROWALKER</div>
        <img src="static/img/sunrise-1756274_1920.jpg" alt="">        
    </div>
<div class="right_bar">
<div class="profile">
    <h1>プロフィール</h1>
    <p>名前：歩<br>
        サイトの中身：思考メモ<br>
        興味：物理、教育、スポーツ<br>
        休日：だいたいPCで色々してる<br>
        </p>
        <a href="about/">もっと読む</a>
</div>            
</div>

<div class="left_bar">
<div class="recent_entries">
    <h1>記事</h1>
    <a href="/articles/">記事を読む</a>
</div>                
</div>
            
<div class="contents">
    <h1>お知らせ・最新情報</h1>
    <li>2019/9/20 ベータ版作成</li>
</div>
</body>

{% endblock %}